services:
  workspace:
    build: ./.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/com.docker.devenvironments.code/build-first-website-with-python/app
    labels:
      dev-environment/service-type: workspace
      dev-environment/service-name: Workspace

  python:
    build: 
      context: ./
      target: dev
    ports:
      - 8000:5000
    volumes:
      - ./app:/usr/local/app
    labels:
      dev-environment/service-type: service
      dev-environment/service-name: Python server

  # mysql:
  #   image: mysql:latest
  #   volumes:
  #     - ./.docker/db:/docker-entrypoint-initdb.d
  #     - mysql-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: superSecret
  #     MYSQL_DATABASE: memes
  #   labels:
  #     dev-environment/service-type: service
  #     dev-environment/service-name: MySQL Database

  # phpmyadmin:
  #   image: phpmyadmin:latest
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_USER: root
  #     PMA_PASSWORD: superSecret
  #   labels:
  #     dev-environment/service-type: service
  #     dev-environment/service-name: phpMyAdmin

volumes:
  mysql-data: